/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.amazon;

public class App {

    public static void main(String[] args) {
        try {
            System.out.println("Initialize Amazon Server.");
            Amazon amazon = new Amazon();
            System.out.println("Run Amazon Server.");
            amazon.run();
        } catch (Exception e) {
            System.out.println("ERROR FOUND!");
            e.printStackTrace();
        }
    }
}
