/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.amazon;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Disabled
    @Test void appHasAGreeting() {
    }
}
